#!/usr/bin/env python3
"""Deterministic contracts codegen — the SSOT -> generated/ step.

Reads contracts/openapi.yaml + contracts/asyncapi.yaml (components.schemas) and
emits:
  - contracts/generated/models.py    (one @dataclass per schema)
  - contracts/generated/manifest.json (canonical field/type manifest; drift anchor)

CI regenerates and `git diff --exit-code`s the output, so hand-edited or drifted
contracts fail the build (audit fix H2). stdlib + PyYAML only — no external codegen.
Deterministic: schemas and fields are emitted in sorted order; no timestamps.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
OPENAPI = ROOT / "contracts" / "openapi.yaml"
ASYNCAPI = ROOT / "contracts" / "asyncapi.yaml"
OUT_DIR = ROOT / "contracts" / "generated"

_SCALARS = {"string": "str", "integer": "int", "number": "float", "boolean": "bool"}


def _pytype(schema: dict) -> str:
    if "$ref" in schema:
        return schema["$ref"].rsplit("/", 1)[-1]
    t = schema.get("type")
    if t in _SCALARS:
        return _SCALARS[t]
    if t == "array":
        return f"list[{_pytype(schema.get('items', {}))}]"
    if t == "object":
        return "dict"
    return "Any"


def _collect_schemas() -> dict:
    schemas: dict[str, dict] = {}
    for spec_path in (OPENAPI, ASYNCAPI):
        spec = yaml.safe_load(spec_path.read_text())
        for name, schema in (spec.get("components", {}).get("schemas", {}) or {}).items():
            if name in schemas and schemas[name] != schema:
                raise SystemExit(f"contract conflict: schema '{name}' defined twice with different shapes")
            schemas[name] = schema
    return schemas


def _fields(schema: dict):
    """Yield (name, pytype, required) sorted: required first, then optional, each A-Z."""
    props = schema.get("properties", {}) or {}
    required = set(schema.get("required", []) or [])
    req = sorted(n for n in props if n in required)
    opt = sorted(n for n in props if n not in required)
    for n in req:
        yield n, _pytype(props[n]), True
    for n in opt:
        yield n, _pytype(props[n]), False


def build():
    schemas = _collect_schemas()
    manifest: dict[str, dict] = {}
    blocks: list[str] = []
    needs_optional = False

    for name in sorted(schemas):
        fields = list(_fields(schemas[name]))
        manifest[name] = {n: {"type": t, "required": r} for n, t, r in fields}
        lines = ["@dataclass", f"class {name}:"]
        if not fields:
            lines.append("    pass")
        for n, t, r in fields:
            if r:
                lines.append(f"    {n}: {t}")
            else:
                needs_optional = True
                lines.append(f"    {n}: Optional[{t}] = None")
        blocks.append("\n".join(lines))

    header = [
        "# GENERATED by scripts/gen_contracts.py — DO NOT EDIT.",
        "# Source of truth: contracts/openapi.yaml, contracts/asyncapi.yaml",
        "from __future__ import annotations",
        "",
        "from dataclasses import dataclass",
    ]
    if needs_optional:
        header.append("from typing import Any, Optional")
    else:
        header.append("from typing import Any")
    models_py = "\n".join(header) + "\n\n\n" + "\n\n\n".join(blocks) + "\n"
    manifest_json = json.dumps(manifest, indent=2, sort_keys=True) + "\n"
    return models_py, manifest_json


def generate(out_dir: Path = OUT_DIR) -> None:
    models_py, manifest_json = build()
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "models.py").write_text(models_py)
    (out_dir / "manifest.json").write_text(manifest_json)
    (out_dir / "__init__.py").write_text("# generated package marker\n")


if __name__ == "__main__":
    generate()
    print(f"generated -> {OUT_DIR.relative_to(ROOT)}/ (models.py, manifest.json)", file=sys.stderr)
